---
- name: Setup load-balancer tier
  hosts: tag_Name_frontend1
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

- name: Setup app tier
  hosts: tag_Name_app1
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}


- name: Setup app tier
  hosts: tag_Name_app1
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

- name: Setup database tier
  hosts: tag_Name_appdb1
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}

- name: Smoke test
  hosts: tag_Name_frontend1
  tasks:
  - uri:
      url: http://127.0.0.1 
      return_content: yes
    register: frontend_result
    failed_when: "'Ansible Deployed Tomcat' not in frontend_result.content" 
