---
# Playbook to Provision AWS Envrioment via Cloudformation Template hosted on OPENTLC.
#
- name: Get the required script
  hosts: workstation
  tasks:
  - name: Create a Dir
    file:
      path: /root/bin
      state: directory

  - name: Download the Script
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/scripts/common.sh
      dest: /root/bin/common.sh
      mode: 0755

  - name: Download 
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/scripts/jq-linux64 
      dest: /root/bin/jq
      mode: 0755

  - name: Download 
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/scripts/order_svc.sh
      dest: /root/bin/order_svc.sh
      mode: 0755

  - name: Import Vars
    include_vars: credentials.yaml

  - name: Order the Environment
    command: "/root/bin/order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y"
    environment:
      username: "{{ username }}"
      password: "{{ password }}"
      uri: "{{ uri }}"

  - name: Wait for VMs to Provision
    pause:
      minutes: 10
